name: CI/CD Pipeline

on:
  push:
    branches: [ main, guillaume_branch ]
  pull_request:
    branches: [ main, guillaume_branch ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create kaggle.json file
      run: |
        echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > kaggle.json
        chmod 400 kaggle.json

    # - name: Set up MLflow
    #   run: |
    #     mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns &

    - name: Run unit tests
      run: |
        python -m unittest discover -v -s tests/unit

    - name: Data folder suppression
      run: |
        if [ -d "./data" ]; then
          rm -rf ./data/*
        else
          echo "Le répertoire 'data' n'existe pas"
          exit 1
        fi

    - name: Models folder suppression
      run: |
        if [ -d "./models" ]; then
          rm -rf ./models/*
        else
          echo "Le répertoire 'models' n'existe pas"
          exit 1
        fi

    # - name: Execute pipeline script
    #   run: |
    #     python ./scripts/pipeline.py
    #     python ./scripts/pipeline.py --test_dataset_mode True

    - name: Run integration tests
      run: |
        python -m unittest discover -v -s tests/integration

    - name: Run Flake8
      run: |
        flake8 src
            
    # - name: Upload test results
    #   uses: actions/upload-artifact@v2
    #   if: always()
    #   with:
    #     name: test-results
    #     path: |
    #       ./logs/*.log
    #       ./mlruns