name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create kaggle.json file
      run: |
        echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > kaggle.json
        chmod 400 kaggle.json

    # - name: Set up MLflow
    #   run: |
    #     mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns &


    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Build Docker images
      run: docker-compose -f /docker/docker-compose.yml build

    - name: Run docker-compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "./docker/docker-compose.yml"

    - name: Execute tests in the running services
      run: |
        docker-compose exec test-app pytest



    # - name: Build and start services
    #   run: docker-compose up -f docker/docker-compose.yml -d
    # - name: Run tests
    #   run: |
    #     # Ajoutez ici vos commandes de test
    #     # Par exemple : curl http://localhost:8080
    # - name: Stop services
    #   run: docker-compose down


    # - name: Set up Docker
    #   uses: docker/setup-buildx-action@v2

    # - name: Run docker compose
    #   run: |
    #     docker-compose -f docker/docker-compose.yml up

    - name: Run Flake8
      run: |
        flake8 .

    - name: Run unit tests
      run: |
        python -m unittest discover -v -s tests/unit

    - name: Data folder suppression
      run: |
        if [ -d "./data" ]; then
          rm -rf ./data/*
        else
          echo "Le répertoire 'data' n'existe pas"
          exit 1
        fi

    - name: Execute pipeline script
      run: |
        python ./scripts/pipeline.py --test_dataset_mode True
    #    python ./scripts/pipeline.py

    - name: Run integration tests
      run: |
        python -m unittest discover -v -s tests/integration
            
    # - name: Upload test results
    #   uses: actions/upload-artifact@v2
    #   if: always()
    #   with:
    #     name: test-results
    #     path: |
    #       ./logs/*.log
    #       ./mlruns
