name: CI/CD Pipeline

on:
  push:
    branches: [ main, guillaume_branch ]
  pull_request:
    branches: [ main, guillaume_branch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create kaggle.json file
      run: |
        echo '{"username":"ruizguillaume","key":"0b5ee4fea04abbfb4fdfed506c3be84d"}' > kaggle.json

    - name: Run unit tests
      run: |
        python -m unittest discover -v -s tests/unit

    - name: Run integration tests
      run: |
        python -m unittest discover -v -s tests/integration

    - name: Execute pipeline script
      run: |
        python ./scripts/pipeline.py --test_dataset_mode True

    - name: Run Flake8
      run: |
        flake8 src
